docker_base:
  image: docker:stable
  tags:
    - build
  services:
    - docker:dind
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE":base -f Dockerfile.base .
    - docker push "$CI_REGISTRY_IMAGE":base
  only:
    changes:
      - Dockerfile.base
