docker_base:
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin "$CI_REGISTRY"
  script: ./scripts/docker-base.sh
  only:
    changes:
      - Dockerfile.base
