language: perl
perl:
  - "5.24"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - zlib1g-dev
      - samtools
      - cpanminus
      - libdist-zilla-perl
      - r-base
install:
  # Install latest gsnap version (with --gunzip support)
  - wget http://research-pub.gene.com/gmap/src/gmap-gsnap-2018-05-30.tar.gz
  - tar -xzvf gmap-gsnap-2018-05-30.tar.gz
  - pushd gmap-2018-05-30 && ./configure --prefix=/usr && make -j4 && sudo make install && popd
  # Install R packages (DESeq2)
  - sudo Rscript install_r_packages.R
  # Install dkpl-annot with Dist-zilla and CPAN-minus
  - dzil install --install-command 'cpanm .'
script:
  - dkpl index -g toy/references/GRCh38-chr22.fa.gz -a toy/references/GRCh38-chr22.gff.gz -i test_index
  - dkpl annot -i test_index --deg toy/dkpl-run/DEGs.tsv.gz toy/dkpl-run/merged-diff-counts.tsv.gz 
  - dkpl annot -i test_index --deg toy/dkpl-run/DEGs.tsv.gz --norm-gene-counts toy/dkpl-run/normalized_counts.tsv --sample-conditions toy/dkpl-run/sample_conditions_full.tsv toy/dkpl-run/merged-diff-counts.tsv.gz