language: perl
perl:
  - "5.24"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - zlib1g-dev
      - samtools
      - cpanminus
      - libdist-zilla-perl
      - r-base
install:
  # Install latest gsnap version (with --gunzip support)
  - echo "deb https://cloud.r-project.org/bin/linux/ubuntu trusty/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update
  - sudo apt-get -y install gmap
  - sudo Rscript install_r_packages.R
  - dzil install --install-command 'cpanm .'
script:
  - dkpl index -g toy/references/GRCh38-chr22.fa.gz -a toy/references/GRCh38-chr22.gff.gz -i test_index
  - dkpl annot -i test_index --deg toy/dkpl-run/DEGs.tsv.gz toy/dkpl-run/merged-diff-counts.tsv.gz 
  - dkpl annot -i test_index --deg toy/dkpl-run/DEGs.tsv.gz --norm-gene-counts toy/dkpl-run/normalized_counts.tsv --sample-conditions toy/dkpl-run/sample_conditions_full.tsv toy/dkpl-run/merged-diff-counts.tsv.gz